Yaapii.Http.sln
appveyor.yml
build.cake

closes #28 
- `build.cake`
- uses loops
- makes NuGet deployment
- `appveyor.yml` remove artifacts and nuget publishing"

Fix NuGet deployment

---

src/Yaapii.Http/Parts/Bodies/JsonBody.Of.cs
tests/Test.Yaapii.Http/Parts/Bodies/JsonBodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/JsonBodyTests.cs

Let JsonBody.Of parse JArray

---

src/Yaapii.Http/Parts/Bodies/Body.Of.cs
src/Yaapii.Http/Parts/Bodies/Body.cs
src/Yaapii.Http/Parts/Bodies/BodyEnvelope.cs
tests/Test.Yaapii.Http/Parts/Bodies/BodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/BodyTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/BytesBodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/BytesBodyTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/HtmlBodyTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/JsonBodyTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/TextBodyTests.cs

Make Bodies use Base64 encoding

---

src/Yaapii.Http/Parts/Bodies/JsonBody.Of.cs
tests/Test.Yaapii.Http/Parts/Bodies/JsonBodyOfTests.cs

jsonbodyof uses bodyof internally

---

src/Yaapii.Http/Responses/ExpectedStatus.cs
tests/Test.Yaapii.Http/Responses/ExpectedStatusTests.cs

Let ExpectedStatus only build Exception when necessary

---

src/Yaapii.Http/Parts/Bodies/Body.FallbackOf.cs
src/Yaapii.Http/Parts/Bodies/FormParams.cs
src/Yaapii.Http/Parts/Uri/Address.cs
src/Yaapii.Http/Parts/Uri/Fragment.cs
src/Yaapii.Http/Parts/Uri/Host.cs
src/Yaapii.Http/Parts/Uri/Path.cs
src/Yaapii.Http/Parts/Uri/Port.cs
src/Yaapii.Http/Parts/Uri/QueryParam.cs
src/Yaapii.Http/Parts/Uri/QueryParams.cs
src/Yaapii.Http/Parts/Uri/Scheme.cs
src/Yaapii.Http/Parts/Uri/User.cs
tests/Test.Yaapii.Http/Parts/Bodies/BodyFallbackOfTests.cs

closes #34 
also adds some useful constructors to existing classes

Add Fallback Body

---

src/Yaapii.Http/Yaapii.Http.csproj

update to Yaapii.JSON 12.1

---

readme.md

Add Elegant Objects badge to readme.md

---

readme.md
src/Yaapii.Http/Facets/JsonEnvelope.cs
src/Yaapii.Http/Parts/Bodies/Body.cs
src/Yaapii.Http/Parts/Bodies/BytesBody.Of.cs
src/Yaapii.Http/Parts/Bodies/JsonBody.Of.cs
src/Yaapii.Http/Parts/Bodies/TextBody.Of.cs
src/Yaapii.Http/Parts/Bodies/XmlBody.Of.cs
tests/Test.Yaapii.Http/Parts/Bodies/BytesBodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/JsonBodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/TextBodyOfTests.cs
tests/Test.Yaapii.Http/Parts/Bodies/XmlBodyOfTests.cs

Add specialized body *.Of classes

---

readme.md
src/Yaapii.Http/Parts/Bodies/TextBody.Of.cs
tests/Test.Yaapii.Http/Parts/Bodies/TextBodyOfTests.cs

Make TextBody.Of work with encodings other than UTF-8

---

src/Yaapii.Http/Facets/FilteredDictionary.cs
src/Yaapii.Http/Facets/MappedDictionary.cs
src/Yaapii.Http/Mock/Templates/Match.cs
src/Yaapii.Http/Parts/Bodies/FormParams.Of.cs
src/Yaapii.Http/Parts/Headers/Headers.Of.cs
src/Yaapii.Http/Parts/Headers/Headers.cs
src/Yaapii.Http/Parts/Uri/Address.Of.cs
src/Yaapii.Http/Parts/Uri/QueryParams.Of.cs
src/Yaapii.Http/Wires/AspNetCoreWire.cs
src/Yaapii.Http/Yaapii.Http.csproj
tests/Test.Yaapii.Http/Parts/ConditionalTests.cs
tests/Test.Yaapii.Http/Responses/FormResponseOfTests.cs
tests/Test.Yaapii.Http/Responses/FormResponseTests.cs
tests/Test.Yaapii.Http/Responses/ResponseTests.cs

Bug dictionaries are enumerated

---

src/Yaapii.Http/Fake/FkWire.cs
src/Yaapii.Http/Wires/Verified.cs

FkWire has ambiguous ctor parameter names
closes #69

fix: avoid ctor ambiguity

---

.editorconfig
build.cake

closes #71 
- Update editorconfig file
Create symbol nuget package in the new format (.nupkg)
Publish symbol packages to nuget.org

Deploy symbols nuget package on Nuget

---

src/Yaapii.Http/Fake/FkAspHttpClients.cs
src/Yaapii.Http/Fake/FkVerification.cs

Add missing fake classes

---

src/Yaapii.Http/Facets/Once.cs
src/Yaapii.Http/Wires/AspNetCore/AspNetCoreClients.cs
src/Yaapii.Http/Wires/AspNetCoreWire.cs
tests/Test.Yaapii.Http/Facets/OnceTests.cs
tests/Test.Yaapii.Http/Wires/AspNetCore/AspNetCoreClientsTests.cs

Set security protocol for http clients

---

src/Yaapii.Http/Wires/AspNetCoreWire.cs
tests/Test.Yaapii.Http/Wires/AspNetCoreWireTests.cs

Encode special characters in form body

---

src/Yaapii.Http/Parts/Bodies/TextBody.Of.cs
src/Yaapii.Http/Parts/Headers/Accept.FirstOf.cs
src/Yaapii.Http/Parts/Headers/Authorization.FirstOf.cs
src/Yaapii.Http/Parts/Headers/BasicAuth.FirstOf.cs
src/Yaapii.Http/Parts/Headers/BearerTokenAuth.FirstOf.cs
src/Yaapii.Http/Parts/Headers/ContentType.FirstOf.cs
src/Yaapii.Http/Parts/Headers/Header.FirstOf.cs
src/Yaapii.Http/Parts/Method.Of.cs
src/Yaapii.Http/Parts/Uri/Address.Of.cs
src/Yaapii.Http/Parts/Uri/Fragment.Of.cs
src/Yaapii.Http/Parts/Uri/Host.Of.cs
src/Yaapii.Http/Parts/Uri/Path.Of.cs
src/Yaapii.Http/Parts/Uri/Port.Of.cs
src/Yaapii.Http/Parts/Uri/QueryParam.Of.cs
src/Yaapii.Http/Parts/Uri/Scheme.Of.cs
src/Yaapii.Http/Parts/Uri/User.Of.cs
src/Yaapii.Http/Responses/Reason.Of.cs
src/Yaapii.Http/Responses/Status.Of.cs

Improve error messages for missing response/request parts

---

src/Yaapii.Http/Wires/AspNetCoreWire.cs
tests/Test.Yaapii.Http/HtAction.cs
tests/Test.Yaapii.Http/Test.Yaapii.Http.csproj
tests/Test.Yaapii.Http/Wires/AspNetCoreWireTests.cs

Fix duplicate header values

---

src/Yaapii.Http/Wires/AspNetCoreWire.cs
tests/Test.Yaapii.Http/Wires/AspNetCoreWireTests.cs

tolerate unsupported headers

---

build.ps1
src/Yaapii.Http/Atoms.Temp/MapOf.cs
src/Yaapii.Http/Parts/Uri/QueryParams.cs
tests/Test.Yaapii.Http/Mock/HttpMockTests.cs
tests/Test.Yaapii.Http/Parts/Uri/QueryParamsTests.cs

Working with empty query

---

appveyor.yml

Refresh nuget token in appveyor.yml

---

src/Yaapii.Http/Parts/Headers/Headers.Of.cs
src/Yaapii.Http/Verifications/Joined.cs
src/Yaapii.Http/Yaapii.Http.csproj
tests/Test.Yaapii.Http/Test.Yaapii.Http.csproj

Repo uses old Atoms and Yaapii.Xml
It uses Atoms 2.6.0 and Yaapii.Xml 1.1.0

Update atoms to 2.6.0

---

src/Yaapii.Http/Responses/Synced.cs
src/Yaapii.Http/Yaapii.Http.csproj

Requests can get stuck in a deadlock.
Deadlocks are avoided using 3rd party library.
Closes #97

Avoid deadlocks

---

src/Yaapii.Http/Wires/Retry.cs
src/Yaapii.Http/Wires/Verified.cs
tests/Test.Yaapii.Http/Mock/HttpMockTests.cs

There are still some objects which do not avoid deadlocks.
All objects avoid deadlocks.
Closes #100

Avoid more deadlocks

---

src/Yaapii.Http/Wires/AspNetCoreWire.cs

closes #102 
Deadlocks are avoided.

Avoid another deadlock when sending

---

src/Yaapii.Http/Yaapii.Http.csproj

add strong named refs

---

src/Yaapii.Http/Yaapii.Http.csproj

remove strong naming

---

build.cake

Remove release maanger

---

src/Yaapii.Http/Yaapii.Http.csproj

See #134
closes #134
The assembly is now strong-named.

Enable strong-naming

---

build.cake
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
src/Yaapii.Http/Yaapii.Http.csproj
tests/Test.Yaapii.Http.Mock/Test.Yaapii.Http.Mock.csproj

Include dlls of other .csprojs in Yaapii.Http NuGet package

---

src/Yaapii.Http.Mock/HttpMock.cs
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http.Mock/HttpMockTests.cs

Fix request address building in HttpMock

---

src/Yaapii.Http.Mock/HttpMock.cs
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http.Mock/HttpMockTests.cs

See #142
closes #142
depends on #141

Fix HttpMock not returning a stream from a fake wire more than once

---

src/Yaapii.Http.Mock/HttpMock.cs
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http.Mock/HttpMockTests.cs
tests/Test.Yaapii.Http.Mock/Test.Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http/Test.Yaapii.Http.csproj

See #144
closes #144
depends on #141 
depends on #143

Enable strongnaming in unit tests to test that strongnaming works

---

src/Yaapii.Http.Mock/HttpMock.cs
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
src/Yaapii.Http/Yaapii.Http.csproj
tests/Test.Yaapii.Http.Mock/HttpMockTests.cs
tests/Test.Yaapii.Http.Mock/Test.Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http/Test.Yaapii.Http.csproj

See #146
closes #146
depends on #141 
depends on #143 
depends on #145

Build for netstandard2.0 and net6

---

readme.md
src/Yaapii.Http.Mock/HttpMock.cs
src/Yaapii.Http.Mock/Yaapii.Http.Mock.csproj
src/Yaapii.Http/Yaapii.Http.csproj
tests/Test.Yaapii.Http.Mock/HttpMockTests.cs
tests/Test.Yaapii.Http.Mock/Test.Yaapii.Http.Mock.csproj
tests/Test.Yaapii.Http/Test.Yaapii.Http.csproj

See #148
closes #148
depends on #141
depends on #143
depends on #145
depends on #147

Support HTTPS in HttpMock

---

build.cake
src/Yaapii.Http/Wires/Retry.cs
tests/Test.Yaapii.Http/Wires/RetryTests.cs

Add optional delay to Wires.Retry

---

src/Yaapii.Http/Parts/Uri/Address.cs
tests/Test.Yaapii.Http/Parts/Uri/AddressTests.cs

Don't add empty path in Address part

---

src/Yaapii.Http/Wires/AspNetCore/AspNetCoreClients.cs
tests/Test.Yaapii.Http/Wires/AspNetCore/AspNetCoreClientsTests.cs

Support automatic response content decompression
